package cn.jambin.model;


/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AlsRating extends BaseAlsRating<AlsRating> {
	public static final AlsRating dao = new AlsRating().dao();
}
