package cn.jambin.model;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseAlsRating<M extends BaseAlsRating<M>> extends Model<M> implements IBean {

	public M setId(Long id) {
		set("id", id);
		return (M)this;
	}

	public Long getId() {
		return getLong("id");
	}

	public M setUserId(Integer userId) {
		set("userId", userId);
		return (M)this;
	}

	public Integer getUserId() {
		return getInt("userId");
	}

	public M setBookId(Integer bookId) {
		set("bookId", bookId);
		return (M)this;
	}

	public Integer getBookId() {
		return getInt("bookId");
	}

	public M setRating(Double rating) {
		set("rating", rating);
		return (M)this;
	}

	public Double getRating() {
		return getDouble("rating");
	}

}
