package cn.jambin.model;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseAlsRating<M extends BaseAlsRating<M>> extends Model<M> implements IBean {

	public M setId(Long id) {
		set("id", id);
		return (M)this;
	}

	public Long getId() {
		return getLong("id");
	}

	public M setUserId(Integer userId) {
		set("user_id", userId);
		return (M)this;
	}

	public Integer getUserId() {
		return getInt("user_id");
	}

	public M setBookId(Integer bookId) {
		set("book_id", bookId);
		return (M)this;
	}

	public Integer getBookId() {
		return getInt("book_id");
	}

	public M setRating(Double rating) {
		set("rating", rating);
		return (M)this;
	}

	public Double getRating() {
		return getDouble("rating");
	}

	public M setCtime(java.util.Date ctime) {
		set("ctime", ctime);
		return (M)this;
	}

	public java.util.Date getCtime() {
		return get("ctime");
	}

}
